# modules/apps/base.nix — system-wide packages for all hosts
{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    nano
    git
    wget
    brave
    chatgpt
    spotify
    discord
    neovim
    kdePackages.kate
    obsidian
    pinentry-curses
    _1password-gui
    jetbrains.idea
    gnupg
    pinentry-gnome3
    kdePackages.plasma-browser-integration
    openjdk21
    firefox
    google-chrome
    kdePackages.kalarm
    gnome-pomodoro
    kdePackages.kaccounts-integration
    kdePackages.kaccounts-providers
    kdePackages.akonadi
    kdePackages.akonadi-mime
    kdePackages.korganizer
    kdePackages.kdepim-addons
    kdePackages.kmail
    kdePackages.kdepim-runtime
    usbutils
    udiskie
    udisks
    chromium
    lm_sensors
    vlc
    syncthing
    syncthingtray
    bluez
    bluez-tools
    bluez-experimental
    godot-mono
    displaylink
  ];
}
